### ISSUE TITLE
training/lessons/articles/tuya_calibration.txt

### ISSUE THREAD

**Issue by bublikOff** [kvazis/training#8]
Несколько перегруженный вариант кондиций ... системе несколько раз приходится пересчитывать чтобы проверить на разницу в 0.5 и в -0.5 ... хотя можно не нагружать систему расчетами лишними

```
  condition:
    - condition: template
      value_template: >-
        {% set v = (((states.sensor.kitchen_climat_temperature.state | float) - (state_attr('climate.kitchen_thermostat', 'local_temperature') | float)) | round(1)) %}
        {{ v >= 0.5 or v <= -0.5 }}
```
вместо

```
condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{ states.sensor.temperature_sensor_spalnya_temperature.state | float | round(1) - state_attr("climate.thermostat_spalnya", "local_temperature") | float | round(1) > 0.5 }}'
        - condition: template
          value_template: '{{ states.sensor.temperature_sensor_spalnya_temperature.state | float | round(1) - state_attr("climate.thermostat_spalnya", "local_temperature") | float | round(1) < -0.5 }}'

```

PS
Опять же излишнее кол-во раз округление ... 
Так же я бы добавил еще одно ограничение ... летом лишний раз гонять термостат нет смысла ... особенно если говорить о городской квартире. Летом отопления в трубах нет ... 

```
    - condition: template
      value_template: >
        {% set n = now() %}
        {{ n.month >= 9 or n.month <= 4 }}

```

Заодно на лето я бы так же уводил термостат в режим OFF чтобы опять же не гоняло лишний раз ее туда сюда 

PPS
Опять же  не скажу за SEA801 ... но например SEA802 калибровка идет в пределах 1 градуса без возможности установить 0.5 или 0.6 и тп ... т.е не понятно зачем проверять условие разницы в 0.5 .... условие 0.5 сработает передвинем допустим на +1 градус что создаст через 10 минут обратный эфект и оно будет уже двигать температуру обратно ... так и будет туда сюда жужжать термостатом  надо проверять в минимуме на разницу >= +1 или -1 градус
